# Generated by Django 5.2.4 on 2025-08-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuariobaneado',
            name='baneado_por',
        ),
        migrations.RemoveField(
            model_name='usuariobaneado',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='UsuarioBaneado',
        ),
    ]
